config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'properties#index'
  resources :properties, only: [:index, :create, :update]

  get 'properties/:id', to: 'properties#index'
  get 'properties/actions/update_details_fields', to: 'properties#update_details_fields'
end

app/models/property.rb
class Property
  include Mongoid::Document

  validates :address, :presence => true
  belongs_to :user

  field :state, type: String
  field :address, type: String
  field :roof_type, type: String
  field :selling, type: Boolean, default: false
  field :details, type: Hash

  def get_status
    status = (self.selling == true)? 'For Sale': 'Pending'
  end

  def get_completeness
    completeness = ((4 - self.get_missing_fields.count)/4.0 * 100).to_int
  end

  def get_missing_fields
    missing_fields = []

    if self.roof_type.blank?
      missing_fields.push(:roof_type)
    end

    unless self.details.nil?
      self.details.each do |key, value|
        if value.blank?
          missing_fields.push(key)
        end
      end
    end

    return missing_fields
  end

  private
    def details_empty
      if self.details.nil?
        errors.add("details", "cannot be empty")
      else
        self.details.each do |k, v|
          if v.blank?
            errors.add(k, "cannot be empty")
          end
        end
      end
    end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  has_many :properties, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!

  def index
    prop_id = params[:id]
    property = nil
    state = nil

    if prop_id
      property = Property.find(prop_id)
      state = property.state
    else
      property = Property.new
    end

    initialize_vars(property, state)

    @current_tab = 'property'
  end

  def create
    @property = Property.new(property_params)
    @property.user = current_user

    if @property.save
      initialize_vars(@property, @property[:state])

      @current_tab = 'sell'
      # flash.now[:success] = "Property created successfully"
    else
      initialize_vars(@property, @property[:state])

      @current_tab = 'property'
      # flash.now[:danger] = "Failed to create property"
    end

    render 'index'
  end

  def update
    @property = Property.find(params[:id])
    @current_tab = params[:property][:current_tab]

    if @current_tab == 'sell'
      if @property.get_missing_fields.any?
        initialize_vars(@property, @property[:state])
        @property.errors.add('Property', 'should be 100% complete to be submitted for selling')

        render 'index'
        return
      end
    end

    if @property.update_attributes(property_params)
      if @current_tab == 'sell'
        @current_tab = 'properties'
        @property = Property.new
      else
        @current_tab = 'sell'
      end

      initialize_vars(@property, @property[:state])
    else
      initialize_vars(@property, @property[:state])
    end

    render 'index'
  end

  def update_details_fields
    initialize_vars(Property.new, params[:state])
  end

private
  def initialize_vars(property, state)
    @properties = current_user.properties.all
    @property = property
    @states = get_property_states

    state = params.try(:fetch, :state, @states.first) if state.nil? else state

    @details_fields = get_details_fields(state)
  end

private
  def get_property_states
    PropertyConfig::PROPERTY_DETAILS_FIELDS.keys.sort
  end

private
  def get_details_fields(state)
    details = PropertyConfig::PROPERTY_DETAILS_FIELDS
    details.try(:fetch, state, {}).try(:fetch, 'details', {})
  end

private
  def property_params
    state = params[:property].try(:fetch, :state, '')
    details_keys = get_details_fields(state).keys

    params.require(:property).permit(:state, :address, :roof_type, :selling, details: details_keys)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListingSpark Exam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css' %>
  </head>

  <body>
    <div class="container">
      <div class="notice"><%= notice %></div>
      <div class="alert"><%= alert %></div>

      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/properties/_errors.html.erb
<% prop.errors.full_messages.each do |message| %>
  <%= content_tag(:div, message, class: "alert alert-danger") %>
<% end %>

app/views/properties/_properties.html.erb
<table class="table table-borderless">
  <tbody>

    <% properties.each do |p| %>
      <tr>
        <td><%= p.address %></td>
        <td class="text-right"><%= link_to p.get_status + ' >>', properties_path(:id => p.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/properties/_property.html.erb
<%= render 'errors', prop: prop %>

<%= form_for prop do |f| %>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.select :state, states.map {|v| [v,v]}, {}, remote: true %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :roof_type %>
    <%= f.text_field :roof_type, class: "form-control" %>
  </div>

  <fieldset>
    <%= render "properties/details/details_fields", form: f, details: prop.details, details_fields: details_fields %>
  </fieldset>

  <%= f.hidden_field :current_tab, :value => 'property' %>
  <%= f.submit 'Save', class: "btn btn-primary" %>
<% end %>

app/views/properties/_sell.html.erb
<% unless prop.address.blank? %>
  <%= render 'errors', prop: prop %>

  <h1><%= prop.address %></h1>

  <h4><%= prop.get_completeness %>% Complete</h4>

  <% if prop.get_missing_fields.any? %>
    <div>Missing Fields:</div>

    <ul>
      <% prop.get_missing_fields.each do |field| %>
        <li><%= field.to_s.titlecase %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for prop do |f| %>
    <%= f.hidden_field :current_tab, :value => 'sell' %>
    <%= f.hidden_field :selling, :value => true %>
    <%= f.submit 'Sell', class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/properties/details/_details_fields.html.erb
<%= form.fields_for :details, OpenStruct.new(details) do |builder| %>
  <% details_fields.each do |key, value| %>
    <%= render "properties/details/fields/#{value['type']}_field", field: value, f: builder %>
  <% end %>
<% end %>

app/views/properties/details/fields/_boolean_field.html.erb
<div class="form-group">
  <%= f.check_box field['name'] %>
  <%= f.label field['name'] %>
</div>

app/views/properties/details/fields/_integer_field.html.erb
<div class="form-group">
  <%= f.label field['name'] %><br />
  <%= f.number_field field['name'] %>
</div>

app/views/properties/index.html.erb
<ul class="nav nav-tabs justify-content-center" role="tablist">
  <li class="nav-item">
    <a class="nav-link <%= @current_tab == 'property'? 'active': '' %>" data-toggle="tab" href="#property">Property</a>
  </li>

  <li class="nav-item">
    <a class="nav-link <%= @current_tab == 'sell'? 'active': '' %>" data-toggle="tab" href="#sell">Sell</a>
  </li>

  <li class="nav-item">
    <a class="nav-link <%= @current_tab == 'properties'? 'active': '' %>" data-toggle="tab" href="#properties">Properties</a>
  </li>
</ul>

<div class="tab-content border border-top-0">
  <div id="property" class="container tab-pane <%= @current_tab == 'property'? 'active': 'fade' %>"><br>
    <%= render "property", prop: @property, states: @states, details_fields: @details_fields %>
  </div>

  <div id="sell" class="container tab-pane <%= @current_tab == 'sell'? 'active': 'fade' %>"><br>
    <%= render "sell", prop: @property %>
  </div>

  <div id="properties" class="container tab-pane <%= @current_tab == 'properties'? 'active': 'fade' %>"><br>
    <%= render "properties", properties: @properties %>
  </div>
</div>

app/views/properties/update_details_fields.js.erb
'<%= form_for(@property) do |ff| %>'
  $("fieldset").html("<%= j (render :partial => 'properties/details/details_fields', locals: {form: ff, details: @property.details,  details_fields: @details_fields}) %>")
'<% end %>'